name: gtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cd build && make -j4
    - name: run
      run: /home/runner/work/6502-emulator/6502-emulator/build/test/em6502test /home/runner/work/6502-emulator/6502-emulator/bin_files/6502_functional_test.bin
